### ISSUE TITLE
Alternative ways to authenticate users

### ISSUE THREAD

**Issue by stian-overasen** [vippsas/vipps-login-wordpress#22]
Having more ways to authenticate users other than the e-mail address would be a great addition to this plugin. In some cases the WordPress users might be registered with a business email and not the private email address from Vipps but still have the same phone number in both systems.

If you would consider adding a filter on line 1000 in `VippsLogin.class.php`, for example something like this:
```php
$user = apply_filters( 'login_with_vipps_authenticate_user', get_user_by( 'email', $email ), $userinfo );
```
… then we could lookup users by `$userinfo['phone_number']` or any other meta value.

ref:
https://github.com/vippsas/vipps-login-wordpress/blob/4460e3612b46c07aaac950abd95a16754870afe9/VippsLogin.class.php#L1000

**Comment by stian-overasen** [comment]
I see that a colleague of mine requested the same thing a while back. This issue is a duplicate of #14

**Comment by iverok** [comment]
I agree,  and in fact there is an open ticket for this: https://github.com/vippsas/vipps-login-wordpress/issues/14 . 

The main reason we haven't done this is because of uncertainty about how we should handle the situation where the Vipps verified email address is already present in the system, as well as how to handle the users email address if the user exists and the current email address is different from the existing one.

Adding the filter above is step 1 (and we are certainly going to do this at some point) but we haven't had the time to map out the different edgecases when the email address is already "in use" in WP. As you know, it is unique and its uniqueness is enforced.

If you have done this work, it would be great to see your preferences here.

It is of course possible to just add the filter and let the users of the filter handle these cases.  If you are prepared to handle this, I can get it in by next monday probably.

**Comment by iverok** [comment]
(The obvious use of this filter would be to use the vipps phone number, so given a sound way of handling duplicate users etc, that would be a setting.  We might add a table too, just for indexing users by vipps id.)

**Comment by stian-overasen** [comment]
You have some valid concerns there.

In our case looking up users by phone number would still be the secondary alternative to email but I don't what implications that may arise by adding this filter.

I hope you get some time to look into this. Looking forward to seeing what you come up with.  :thumbsup:

**Comment by stian-overasen** [comment]
Any news on this @iverok ?

**Comment by iverok** [comment]
No, status is as before: Easy to implement a hook for this, not that easy to handle all edge cases. If you are willing to act as a test subject for this, I can add the hooks and some default, hopefully safe, behaviour within about a month I think.

**Comment by iverok** [comment]
We've updated ticket #14 with a proposal now if you have comments.
