### ISSUE TITLE
Multisite settings

### ISSUE THREAD

**Issue by pdewouters** [vippsas/vipps-login-wordpress#25]
Hi, it would be great if the setings could be set on the network level, because I'm using the plugin on a 300+ site network, meaning I have to either set them manually or write some code to clone the settings from the main site

Looks like I would need to add all the site URLs in the vipps portal as well,... so doesn't seem a good option

**Comment by iverok** [comment]
Yes, you would still have to register the landing pages manually unfortunately.  I do expect that there will eventually be an API for this setup job from Vipps, making it automate-able; but it won't happen soon.

Also unfortunately, we can't prioritize creating a global setup screen like this right now, so I think scripting it is probably your best option (for the keys and such). 
All the settings are in the <prefix>_options table with the keys

```
continue_with_vipps_options
vipps_login_options
vipps_login_options2
vipps_login_woo_options
```

so the easiest would be to use wp-cli with the "options" command to set the option for all sites. But you will still need to create the landing URLs.

Another approach for the settings would be to  use the ["option_" hook in wordpress](https://developer.wordpress.org/reference/hooks/option_option/) to override these settings with a global set  in a network-enabled plugin.   You could in this hook use ` get_current_blog_id() `  to discriminate between the sites, set the options in one distinguished site, and for the other sites, just get the values from the chosen one.

**Comment by pdewouters** [comment]
ok thanks, yes I wrote the CLI command similar to what you describe. maybe the vipps portal allows for wildcard subdirectories? so we don't have to create an entry for each subsite

**Comment by pdewouters** [comment]
@iverok do you think each subsite needs its own landing page or could I redirect users to the main site to login and then redirect them back to the subsite on successful login?

**Comment by iverok** [comment]
Wildcards: It does not. Sorry.

A single landing page for all: I think that could work, but it probably can't do the login because there are cookies involved for the logging-in and for checking that the sessions are correct.

It might work though to just redirect to the correct subsite with the same arguments - they are passed as query strings - so you would then only need to write some code that allows you to find the correct blogid at that point. You could do this in a template_redirect hook on the landing-page site.

Unfortunately, to make that work you would need to modify the code a bit, since the only one of these arguments that can be controlled is the "state" one. In the code, this parameter is set to a string consisting of the action name (such as "login"), a double colon separator "::" and then the login session id.   There are no filters for this at the moment. You could define your own "action" but it would be a lot of work.

I guess a fairly clean approach would be to add an action to VippsSession, so that when a session is generated, a `set_site_transient` is created network-wide from the session key to the blog id.  Then the landing page trampoline could look up where the session was stored, and redirect to that sites returnhandler - which would log the user in etc.

That is, a 

`   do_action('vipps_login_session_created', $sessionkey);`

at around line 96 in VippsSession .

Let me know if you want to try to implement this; I can then probably add the neccessary hooks to the main plugin. Unfortunately we won't be able to implement or test this ourselves at this point.

**Comment by pdewouters** [comment]
thanks, really appreciate you taking the time to write this detailed explanation and suggestions.

**Comment by pdewouters** [comment]
@iverok related question - do you know if the plugin should be network activated or activated per site only?

**Comment by iverok** [comment]
It shouldn't matter, so I would say network. You will still need to add settings for every subsite.
